/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MicrophoneCapture {
  constructor(deviceId?: string | undefined | null)
  /**
   * EMITTED sample rate — the rate of the PCM handed to STT (16000 when the
   * resampler is active). Declare THIS to STT providers.
   */
  getSampleRate(): number
  /**
   * NATIVE hardware rate (e.g. 24000 for AirPods HFP, 48000 built-in) — for
   * diagnostics and HFP/Bluetooth-degradation detection only.
   */
  getNativeSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null): void
  stop(): void
}

export declare class SystemAudioCapture {
  constructor(deviceId?: string | undefined | null)
  /**
   * EMITTED sample rate — the rate of the PCM handed to STT (16000 when the
   * resampler is active). This is what callers must declare to STT providers.
   */
  getSampleRate(): number
  /**
   * NATIVE hardware sample rate (e.g. 48000) — for diagnostics and
   * HFP/Bluetooth-degradation detection only. NOT the rate of emitted bytes.
   */
  getNativeSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null): void
  stop(): void
}

export declare function applyStealthToWindow(handle: Buffer): void

export interface AudioDeviceInfo {
  id: string
  name: string
}

/**
 * Returns the platform-native ID of the current default output device.
 * macOS: CoreAudio device UID. Windows: WASAPI device id (eMultimedia/eConsole role).
 * Empty string on error or unsupported platform.
 *
 * JS polls this every few seconds during an active meeting; when the value
 * changes, main.ts recreates SystemAudioCapture so the CoreAudio Tap follows
 * the new output route. Without this, switching output devices mid-meeting
 * (plug in headphones, swap AirPods, route to virtual cable) leaves the tap
 * bound to the original device, capturing silence.
 */
export declare function getDefaultOutputDeviceId(): string

export declare function getInputDevices(): Array<AudioDeviceInfo>

export declare function getOutputDevices(): Array<AudioDeviceInfo>

export declare function getPressedShortcutKey(): ShortcutKeyInput | null

export declare function removeStealthFromWindow(handle: Buffer): void

export interface ShortcutKeyInput {
  key: string
  ctrlKey: boolean
  altKey: boolean
  shiftKey: boolean
  metaKey: boolean
}
